# Generated by Django 3.2.11 on 2022-01-19 07:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20220119_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='msrp',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
