# Generated by Django 3.2.11 on 2022-01-19 07:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_msrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='msrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
