# Generated by Django 3.2.11 on 2022-01-19 12:59

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
